### PR TITLE
Replace outdated simulation methods

### PR DESCRIPTION
**Pull request by vgregory757**
The latest update (due to [this](https://github.com/QuantEcon/QuantEcon.jl/pull/137)) broke some of the existing Markov chain simulation code in this repo. I replaced the outdated methods with the new ones.

### CODE REVIEW

**Comment by jstac** [comment]
@vgregory757 Thanks for working on this!  I completely forgot.  

Would you mind to check on this too, from `arellano_vfi.jl`

```
    y_sim_indices = simulate(mc, initial_dist, capT+1)`
```

and 

```
   y_sim_indices = simulate(mc, capT+1, y_init_ind)
```

**Comment by jstac** [comment]
@spencerlyon2 Am I right in saying that the new simulation functions for MarkovChain aren't released yet?  In which case we shouldn't merge this until they are.  

When you do update the package, would you mind to let me know?

**Comment by spencerlyon2** [comment]
They are live! Officially published [here](https://github.com/JuliaLang/METADATA.jl/commit/adacaf76c99dc208440264af925fd2e7a94cbb5e)

**Comment by jstac** [comment]
@vgregory757 @spencerlyon2 Thanks guys!

**Pull request merged**
