### PR TITLE
Adding julia models package into _jllib_/ and updated arellano notebo…

### PR DESCRIPTION
**Pull request by mmcky**
…ok to run by @spencerlyon2 

This PR adds in the Julia ``Models`` subpackage from QuantEcon.jl/src/Models.jl as part of ``migrate-applications`` project to ``QuantEcon.applications``

@spencerlyon2 I have only changed one notebook in the ``arellano`` to see if you are happy with these modifications for importing ``Models.jl``. The python side has the python modules in each respective folder to support local imports.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Hey @mmcky the changes here look good to me.

Let's update the other notebooks to have the same `include("../_jllib_/Models.jl"); using .Models` line and we should be good to go.

**Comment by mmcky** [comment]
@spencerlyon2 Hey Spencer. While this solution works - I spoke with John yesterday afternoon and we came up with another solution that is straight forward and harmonizes code between Python and Julia. While I don't think we need to always keep the two in ``sync`` as they are designed in different ways - I do think it makes sense in this case. 

What the proposal is:

Simply break up the Models.jl package and locate the relevant code in each topic folder which allows the use of ``using`` without the need to ``include`` to some other location.

Do you see any possible issues with this approach?
We are running through the python side to ``dedup`` any code by merging relevant topic folders such as ``opt_tax_recur/`` and ``amss/``.

**Comment by spencerlyon2** [comment]
That should be fine.

I think we will probably want to use `include` instead of `using` in that case.

Let me know if you run into any problems with this approach.

**Comment by mmcky** [comment]
@spencerlyon2 Great - thanks for the feedback.
I will work on this later this afternoon.

**Comment by mmcky** [comment]
@spencerlyon2 When you get a chance. I have updated the ``arellano`` example based on the latest proposed structure. It works well. 

One thing I noticed is that the heatmap no longer generates. Is this a package update issue? or have I upset the image generation due to no longer importing Models.jl package?

**Comment by spencerlyon2** [comment]
Hey @mmcky I tried looking at this (and seeing why the heatmap doesn't work) and am getting issues loading Gadfly. 

I don't have time to investigate right now, but I'll try to take a look later today. Thanks

**Comment by mmcky** [comment]
Thanks @cc7768  and @spencerlyon2 for your input here.

**Comment by cc7768** [comment]
@spencerlyon2 @mmcky I don't know if you saw, but I got a shortcut for the heatmap working in that notebook. It is a temporary fix, but it works for now.

For some reason it wanted the `x` and `y` arguments and wasn't happy with the `x_min`, `x_max`, `y_min`, `y_max`. Should sort out why later.

**Comment by mmcky** [comment]
Thanks @cc7768 - I will add that to the issue with the broken notebooks.

**Pull request merged**
