### PR TITLE
Fix models

### PR DESCRIPTION
**Pull request by mmcky**
This PR fixes the lecture supporting code by migrating import statements from ``quantecon.models`` to local modules contained in each lecture folder. This fixes notebooks and associated code files (such as ``test_career.py``)

** Issues:**
  1. **Arellano** needs an update due to updates to tauchen in the latest release of ``quantecon``. 
  1. Julia examples also need to be updated (working on this next).

### CODE REVIEW

**Comment by mmcky** [comment]
The ``Makefile`` adds the commands

  1. ``make test-ipynb`` which will test all ipython notebooks and report those that are broken. [**Note:** Currently this isn't running julia notebooks properly]
  1. ``make test-py`` which will test all py files that are in this ``QuantEcon.applications`` repository. 
  1. ``make test`` tests both ipynb and py files. [**Warning:** this takes quite some time to run]

**Comment by jstac** [comment]
@mmcky Thanks!  Is the next step to add a fetch utility for QuantEcon.applications code to QuantEcon.py and QuantEcon.jl?  In which case should I wait to merge?

**Comment by mmcky** [comment]
@jstac I just paused. I think the next step is to update the ``jl`` side of this repository and then merge this updated material to get the ``git clone`` and ``mybinder`` approach to running the notebooks working. 

I think what you suggest above is the second step and will be pretty easy to implement once everything is back up and running again.

**Comment by mmcky** [comment]
**Julia Issues**

  1. When updating ``optgrowth`` to use ``linspace`` rather than the old ``linspace_range`` causes an issue with ``PyPlot``. If we migrate away from PyPlot then this issue may go away.

**Comment by spencerlyon2** [comment]
@mmcky I have a few minutes to spare. I'll look at the optgrowth notebook right now

**Comment by spencerlyon2** [comment]
I updated optgrowth. It now uses PlotlyJS and Interpolations.

Also, for the first exercise I made an interactive graph that lets you move a slider to show the value function after n iterations, instead of just choosing 3 n's and making a 3 subplot figure.

If we don't want that level of sophistication in the examples, we can easily revert to what we had before.

**Comment by spencerlyon2** [comment]
I should point out that the interactive slider will only work on the current master branch of PlotlyJS.jl.

Once [this PR](https://github.com/JuliaLang/METADATA.jl/pull/5107) is merged, those changes will be active in the released version of PlotlyJS.jl

**Comment by mmcky** [comment]
@jstac this PR currently fixes a number of issues that prevent the current notebooks to run. While a few still remain I think we should go ahead and merge and then I will document what is left to be done from the various posts for the next PR.

**Comment by jstac** [comment]
@mmcky Many thanks.  I'll merge now.

@spencerlyon2 The slider is really cool.  It will be great to get all the plots switched over to PlotlyJS.

**Pull request merged**
