### PR TITLE
More plots

### PR DESCRIPTION
**Pull request by vgregory757**
Another batch of plots with Plots.jl.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Looks great, thanks!

I noticed the `pyplot` backend was used (at least in all the .jl files). Were you having issues with plotlyjs?

**Comment by vgregory757** [comment]
No issues. I just decided to use `pyplot` in cases where the charts had features that aren't yet implemented in `plotlyjs` via `Plots` (such as LaTeX). Once everything is supported, I can easily swap out all the backends :)

**Comment by jstac** [comment]
@vgregory757 Many thanks.  These look great.  (Sorry for the slow response.  I'm traveling with intermittent email.)

@albep Would you mind to test all of these, make sure they run on your machine and provide feedback, if any?

**Comment by albep** [comment]
@vgregory757 Great work, many of those plots are really complicated!

I was able to check all of them, except for plots in `gaussian_contours.jl`. As I don't have a working `PyPlot`, I had to change all of them to `plotlyjs` backend - and the color gradients used in `gaussian_contours.jl` don't work under plotlyjs. Also, `arrow=:true` in `eigenvec.jl` isn't available under plotlyjs, but removing it I was able to run all code.

All other plots run smoothly.

PS: Running the updated codes I noticed that some of them need a couple of fixes unrelated to the plots, due to changes in the QuantEcon functions they rely on. After this PR is merged, I'd be happy to make these changes

**Comment by vgregory757** [comment]
@albep Thanks for checking! Yeah, the fact that not all features needed for the charts were supported for `plotlyjs` was why I mostly used `pyplot` as the backend. Sometimes with `plotlyjs`, you don't even get an error but the formatting is just ignored. So you may not have seen some plots in the way I intended, but they should still look okay despite that.

**Comment by jstac** [comment]
@vgregory757 @albep Thanks guys, this is very helpful.

They are all nicely done.  I'll merge now.

@albep Please go ahead and implement any updates necessary for the code to run.  I saw that you issued a PR already.

**Pull request merged**
