### PR TITLE
Delete "from __future__" from solution notebooks

### PR DESCRIPTION
**Pull request by nswa17**
Address #12
arellano/arellano_solutions_py.ipynb is left untouched since it contains `quantecon.models`

### CODE REVIEW

**Comment by mmcky** [comment]
Anyone know a better way of diffing ``ipynb`` files? Resolving merge conflicts on ``json`` isn't particularly friendly.

**Comment by nswa17** [comment]
I have made a rebase on master. I believe this is ready to merge.

**Comment by mmcky** [comment]
These notebooks pass the notebook execution tests. Should be good to merge.

**Comment by jstac** [comment]
@mmcky Great, please go ahead.  @nswa17 Many thanks.

**Pull request merged**
