### PR TITLE
Minor cleanup of ifp.jl code.

### PR DESCRIPTION
**Pull request by spencerlyon2**
Now uses PlotlyJS for graphics and Interpolations for interp

### CODE REVIEW

**Comment by jstac** [comment]
@spencerlyon2 Many thanks for this.  Julia is broken on my machine at the moment but once it's fixed I'll test.

**Comment by mmcky** [comment]
@spencerlyon2 The rendered graphs look really good!. 

My only comment is that I get loads of `warnings`

```
WARNING: Specifying the method using symbols is deprecated. Use "method = Optim.Brent()" instead
```

**Comment by spencerlyon2** [comment]
Hey @mmcky , good catch.

That comes from a new release of Optim.jl being cut just [3 days ago](https://github.com/JuliaOpt/Optim.jl/releases/tag/v0.4.5).

I'm going to go through this code one more time to simplify it even more. While I'm doing that I'll resolve the warnings.

**Comment by spencerlyon2** [comment]
OK I fixed the code to remove the abstract type and also resolve warnings with Optim.

Side note: the warnings about Combinatorics.jl should be resolved once [this](https://github.com/JuliaLang/Combinatorics.jl/pull/19) is merged and a new Julia 0.4 release of Combinatorics.jl is released (should both happen today or tomorrow).

**Comment by mmcky** [comment]
Nice Graphics! This works well on my machine.

**Comment by spencerlyon2** [comment]
Awesome, glad to hear it.

@jstac does this look mergeble to you now?

**Comment by jstac** [comment]
It looks beautiful.  The code is just the right balance and the graphs look outstanding.  

I'll merge in an hour or two if there are no further comments.

**Pull request merged**
