### PR TITLE
Added Julia versions of discrete_dp and aiyagari

### PR DESCRIPTION
**Pull request by MaximilianJHuber**
I ported the discrete_dp and aiyagari applications of the DiscreteDP toolkit.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
@MaximilianJHuber thank you for working on this.

It might take me a few days to really do a proper review of this code.

@QuantEcon/lead-developers if anyone else gets to it before me I won't be upset :wink:

**Comment by jstac** [comment]
@MaximilianJHuber Many thanks for these contributions!  I've had a look and the code is very nicely written.  Are you happy for me to add Julia lectures on quant-econ.net corresponding to 

http://quant-econ.net/py/discrete_dp.html and http://quant-econ.net/py/aiyagari.html

based on your code?  I'll make a note at the top of each lecture thanking you for contributing.  (Your code will probably end up getting modified to some degree.)

Thanks again for getting involved.  It would be be really great if you could continue pushing forward with optimization of the discrete DP code, as in #118.

cc @thomassargent30

**Comment by MaximilianJHuber** [comment]
@jstac The lectures were a great starting point for me to learn Julia, I am glad that I can give something back.
Please use my code as you see fit and please don't add any acknowledgments to those lectures.

**Comment by jstac** [comment]
@MaximilianJHuber Much appreciated.  I hope we hear more from you.

**Comment by jstac** [comment]
@MaximilianJHuber Just FYI,  we used your code as a basis for a Julia version of the discrete DP lecture:

http://quant-econ.net/jl/discrete_dp.html

You said you didn't need to be thanked but I took the liberty of acknowledging you in the solution notebook:

http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/discrete_dp/discrete_dp_solutions_jl.ipynb

Please let me know if you don't want your name there.

**Pull request merged**
